### ISSUE TITLE
[Wish List]: Blockstack 101 Primer 

### ISSUE THREAD

**Issue by RaffiSapire** [stacksgov/Stacks-Grants#1]
*We prefer clear, concrete, and concise applications. If an application is incomplete or unclear, we will request an update to the application.*

**Background:** What problems do you aim to solve? How does it serve the mission of a user owned internet? 
Because Blockstack introduces so many novel concepts, it can be somewhat daunting for beginners to fully grasp and appreciate what Blockstack is and how it works. There is information across multiple platforms in the form of video, paper, medium, and web copy explaining what Stacks is and how it works. 

**Project Overview:** What solution are you providing? Who will it serve? 
The Primer can serve as a 101 resource for new community members. I'd like to see a creatively illustrated microsite called "Blockstack Primer" or "Blockstack 101" that leverages storytelling, illustration, and copy from previous resources in an effort to cater to visual learners or non-technical learners, and inspires more users to participate in the network.

In terms of style and communication I suggest drawing inspiration from these educational microsites:

https://urbit.org/primer
https://livepeer.org/primer

**Scope:** What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?
The components are copy and illustrations. The final deliverable could be a one-pager that has copy and illustrations. Does this tool help people learn about Blockstack? Success can be measured by google analytics. 

**Budget and Milestones:** What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.
1. Finalize copy and find an illustrator to work with on microsite 2. Wireframe 3. Illustrations 4. Build and make site live 

**Team** This could be a web developer + illustrator. Illustrators do not need to understand crypto or blockstack in a technical way to do a great job on this project. In many ways it's beneficial to have someone who is new to the project to watch a few videos and read a couple things about the project and then come up with characters and a story that explains how it works. 

Resources: 
Find Illustration Freelancers: https://www.womenwhodraw.com/ and https://www.etsy.com/market/illustrator_for_hire

**Comment by friedger** [comment]
The application should contain a concrete budget!

I would define success of the project as: The primer receives 5 positive feedback by community members (technical and non-technical) as well as the primer is published.

Counting page views would be another project around marketing for the site.

**Comment by blocks8** [comment]
This proposal was created as a Wishlist item. Where someone who could create a proposal to fulfill this request would be able propose their own proposal that meets the needs of the wish list. Perhaps there is a better way to define wishlist items so they aren't confused as a proposal. Open to ideas @friedger 

To answer @whoabuddy's questions: 
- should this microsite embrace the upcoming rebrand and use "Stacks" instead of "Blockstack" throughout for the name?
will this microsite be hosted at stacks.org (i.e. stacks.org/primer) or will it be hosted independently? _The latest information would be ideal, as the livepeer example shows, they used the Livepeer logo but the illustrations were original from any Livepeer branding. Could imagine a similar take for Blockstack, so in absence of a new brand, the visuals would be detached from the Blockstack logo_ 
_For hosting, this could live on a separate site and have a redirect via stacks.org to the independent page to make it easy. We would want to retain the illustrations for community use, so a backup copy of the illustrations and the site would be open sourced for future use in case the other website is no longer accessible._

if the former, what considerations does the illustrator/designer need to consider for the site to be implemented via webflow?
if the latter, who will be responsible for hosting and technical implementations, such as analytics? how will those be reported and to whom?
_Open to ideas, can be a collaboration between foundation website and the illustration. Illustrations and content would be the primary request, how to host securely and for the long term is something we could resolve by hosting or working with the proposer._

for analytics, the usage of Google Analytics is not in alignment with the mission of creating a user-owned internet, and often a point of contention in the Stacks ecosystem. Would another solution such as Fathom analytics (in use by some dapps / stacks.org now) or something similar serve the same purpose?
_I think measuring reach is the goal. The type of analytics could be discussed. Open to ideas._

**Comment by Marsdrummer** [comment]
hi everyone, I'm Mark, new to the group here. I have some ideas for how we would tackle this but since it's a wishlist, not a new application, I'm not sure how to begin. We also have relationships with data sci / AI training companies here in Europe that could help with translation and dissemination to targeted groups. @RaffiSapire can you lmk how we can discuss?

**Comment by CodeLaryna** [comment]
This project would help me make a primer for my Crypto Exchange.

**Comment by oiclid** [comment]
Is this still open?

**Comment by MichaelforMichigan** [comment]
This is an excellent idea which would lead to the growth in the Stacks identity, the Stacks holders, and the value of Stacks. 

How do we obtain a grant to do this?

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
