### ISSUE TITLE
ALEX - a higher-level library that allows front-end developers to interact with contracts deployed at ALEX

### ISSUE THREAD

**Issue by fiftyeightandeight** [stacksgov/Stacks-Grants#195]
## Background
`stacks.js` libraries provide everything you need to work with the Stacks blockchain. While it has rich feature sets that make front-end development on Stacks easy, the growth of Stacks ecosystem that builds upon `stacks.js` increases the complexity faced by developers looking to integrate apps available on Stacks ecosystem into their own apps. 

## Project Overview
`alex.js` is a higher-level library that allows front-end developers to interact with contracts deployed at ALEX and encapsulates the lower-level calls to `stacks.js`. This is important for DeFi developer adoption of Stacks ecosystem and may serve as a reference implementation for any Stacks smart contract developers looking to expose similar APIs to other developers.

## Deliverables
**Deliverable**: an umbrella Javascript package that exports all the ALEX tools you need to start building on ALEX. The deliverable will be open sourced.
**Total requested grant** for this deliverable = $30,000
**Deliverable deadline**: Sep 30

- [ ] Contract Calls ($10,000): APIs for contract calls (`define-public`) and error handling
- [ ] Read-Only ($10,000): APIs for read-only functions (`define-read-only`) and error handling
- [ ] Transaction Status Watcher ($5,000): Event dispatcher listening on transaction status change
- [ ] Utils ($5,000): Helper functions useful for developers

![](https://user-images.githubusercontent.com/5652583/128288658-d8e53209-ae09-422b-af43-7307862e3ed2.png)

## Community and Supporting Materials
Two projects of Stacks Accelerator Cohort 1 asked for such APIs so that they can easily integrate ALEX protocols into their product offering. We will be happy to share more details with the Foundation.

**Comment by jennymith** [comment]
Hi @fiftyeightandeight, thanks for resubmitting this milestone as a separate grant! Considering the size of this grant, we have a few questions/points we'd like you to address before we can make a concrete decision.

- Could you please provide a more detailed explanation of the complexity that you plan to abstract away from the smart contracts deployed at ALEX? To be clear, we would not approve this grant if it is just proposing a thin client. 
- Are you able to share more information on the ways in which the Stacks Accelerator teams plan to use ALEX protocols? Are these protocols _critical_ to their product offerings?
- What is the value of releasing this library now instead of later? Would it perhaps make more sense to release this library after the ALEX platform has launched (once you have actual users and have proven that your API could be useful to other developers)?

**Comment by friedger** [comment]
Can [clarigen](https://github.com/obylabs/clarigen) help with some parts of the library? If not, can clarigen be improved to make this library.

**Comment by fiftyeightandeight** [comment]
@friedger thank you for your suggestion. [clarigen](https://github.com/obylabs/clarigen) is very interesting! Let us review and revert.

**Comment by jennymith** [comment]
Hi @fiftyeightandeight I'm sure you had your hands full with the Accelerator Demo Day last week (excellent presentation btw!) but I just wanted to check in on this grant. Let us know if you need any further support/guidance on addressing [these questions](https://github.com/stacksgov/Stacks-Grants/issues/195#issuecomment-915492519)? @friedger's suggestion to look into clarigen is very relevant here.

**Comment by fiftyeightandeight** [comment]
Hi @jennymith @friedger we've reviewed Clarigen and think we can use at least some of the functions in alex.js as well as borrow some of its design. Thank you for your suggestions!
