### ISSUE TITLE
[Wish List] Name certification service

### ISSUE THREAD

**Issue by friedger** [stacksgov/Stacks-Grants#23]
*We prefer clear, concrete, and concise applications. If an application is incomplete or unclear, we will request an update to the application.*

## Background

> What problems do you aim to solve? How does it serve the mission of a user owned internet?
Blockstack usernames can be created and used in a decentralized way. Currently, there is no way to attach additional value to the names like social proofs or other certifications beyond a basic self-certified profile. 

There used to be a social verification service on proof.blockstack.org integrated into the legacy authenticator at browser.blockstack.org but it is not supported anymore.

## Project Overview

> What solution are you providing? Who will it serve?

This project is about 
* creating one certification service/authority for blockstack names
* adding UI to the blockstack app for handling (add, remove, share) certificates by many authorities

**Comment by hozzjss** [comment]
I'm thinking of how that would look like, and I have two models in mind so far, that grow into one another, the first is KYC so that you could be really verified through documentation, and that grows into community members vouching for other identities instead of KYC, something else can be implemented like through the age of the identity for example but that is risky, as you might have people who have signed up just to try stuff and then went away for a very long time, and they come back later after their identity became more valuable, what do you think?

**Comment by friedger** [comment]
The service could also work with https://github.com/stacksgov/sips/pull/57

Gitcoin is using
https://gitcoin.co/profile/trust and https://proofofpersonhood.com/

**Comment by will-at-stacks** [comment]
@friedger very cool!  I would love to hear more about this on our call today.

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
