### ISSUE TITLE
Building stacks developer ecosystem for Japanese 

### ISSUE THREAD

**Issue by enmaidao** [stacksgov/Stacks-Grants#278]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?
As the concepts of Web3.0 and DAO have become widespread and many decentralized projects have emerged, many problems have arisen at the same time. The significant problem is the lack of competent Web3 developers. In addition to the industry itself being still developing, access to different languages and ecosystems is as complex as spaghetti, making it difficult to learn efficiently. However, many projects will be born while learners are looking for reliable sources, and the demand for developers will increase every moment. Our project is to create a platform for holding hackathons and a marketplace for Dapps developed by the team. By doing so, we will create a pool of talented developers who will be able to participate in web3. We can lead developers to the world of Stacks, which is secure and decentralized, yet does not make a big difference in the performance of hardware and the amount of crypto assets.

**Project Overview**
What solution are you providing? Who will it serve?
We will build a P2P hackathon system for developers who want to participate in Web 3.0 to learn technologies including the Stacks chain ecosystem. There, we will provide a marketplace for smooth job matching by visualizing project participation status and achievements. In the conventional centralized system, the fee for job matching is about 20-30%. Furthermore, because of the financial incentives, it was not uncommon for workers' backgrounds to be falsified and forced into matching. The platform, however, prevents malicious impersonation because what users learn and the projects they participate in are cast as NFTs. It is also possible to sell Apps within the platform, and to hold lectures by prominent outside engineers as voted by the users. In other words, it is not just a platform for hackathons, but also a community where many engineers gather. By joining this community, Stacks will have a huge pool of developers.

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

The deliverables will include the translation of the development documentation, including the hiro developers, into Japanese and the organization of a Stacks study group in Japan.
A measure of success will be the development of the Stacks ecosystem in Japan by translating the development documentation and holding Stacks workshops. Specifically, if we can gather about 50 Japanese developers, the workshop will be a success.

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Epic	costs
Phase 1: Translation - Holding study sessions   ->$24,000(this proposal)
Phase 2: Build hackathon platform & Hold Hackathon for Stacks ->Next Grants(March ~ July)
Phase 3: Build marketplace for Stacks Dapps ->Next Grants(July ~)

Total Grant Request: 

Phase1: "Translation - Holding study sessions" 

M1:Cost of Hiro Docs & Stacks Docs translation to Japanese and making sub materials (30days)
M2:Stacks chain learning session (30days)

- Understanding Stacks Docs & Create sample programs (2 engineers)
- Hold study sessions for external parties (1h x 5 sessions expected) ⇒ Attract more than 50 developers per session
- Marketing about various study sessions
    - Explanation of Stacks chain
    - Clarity basics
    - Explanation of Code (Wallet connection, NFT Mint)
    - Clarity implementation tips
    - Deploy Dapps with Stacks

**Funds will be used for**

1. Marketing $10,000
2. Group Usage Fee(DeVillage) $2,000
3. Engineer $6,000
4. Illustrator $1,000
5. Twitter Contents for Stacks Development by Influencer $5,000

**Total Budget** - $24,000

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

Our team has specialists with a variety of skills, including developers, marketers, designers and so on. Since it is a group of members with unique roots, the existence of the team is recognized in a wide range. We carry out activities with striving to achieve the highest quality. Please take a look at our website and the NFTs you actually use.

**member**

Enmai

Enmai has invested in a number of DeFi and NFT products in multiple chain ecosystems, including BSC, FTM, Solana, AVAX, ICP, Stacks, and Moonbeam since January 2021. Enmai has been a moderator and staff member at multiple DAOs, and wants to commit to Web 3.0 and DAO space in 2022 and beyond. Her day job is AI consultant.

ikisuke
ikisuke is a engineer in Web3.0 and a community manager in many crypto discord communities. Currently, Ikisuke is studying web 3.0 engineering, and is mainly looking for information about Stacks. He is also an admin for many communities, so he has knowledge of community management.

Masato

Masato has many years of experience as an embedded system architect and senior engineer at an audio equipment manufacturer. Currently, Masato is the engineering leader of the PC / macOS / iOS / Android application development team at the company, and also hold the post of the CTO for a Web3 startup company.
Taking advantage of many years of development lead experience at manufacturers, Masato will demonstrate abilities not only as an engineer but also as a development director.
Masato is interested in Stacks because Masato feels the potential of the scalability of Stacks chain, which is the programming layer of Bitcoin chain. Masato looks forward to contributing to the recognition and dissemination of Stacks.

Kammy

Kammy is a senior engineer who has been working as an embedded software engineer for many years. In recent years, Kammy has been active in a wide range of fields, from building development environments to developing Web applications.
Having become interested in Block chain technology, Kammy belongs to a Web3 start-up company and study Solidity and Stacks. Kammy promotes the Stacks chain and contributes to the expansion of Bitcoin's potential.

D💎.btc/Ӿ
D is a crypto enthusiast and as an investment banker, he has developed strong interests in how future finance will look like along with adoption of blockchain into the system. As an investor, researcher, promoter, and advisor, he has expanded his activity scope in the world of crypto by closely interacting with various project teams, which he sees true potential and value. D is leading Stacks Japan Chapter and growing the community and ecosystem in Japan. While Japan is still a new frontier for Stacks, the community is growing very fast and strong. He is seeking to localize Stacks ecosystem with the help of their growing community, by diversifying community participants ranging from traders/investors, developers, engineers, entrepreneurs, and even NFT artists.

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

We believe that our platform will continue to work once a certain number of users participate, but we must pay more attention to attracting users at launch. By forming a partnership with a Web 2.0 development company and DAO which plans to use a job matching system, it has been decided to have them participate as initial users. In addition, by compensating for the initial cost of early adopters with the acquired grants, we can expect the activation of the platform and the marketing effect of their SNS transmission activities.

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

Our team includes members who work as freelancers for Web3.0, members who have connections with large Web2.0 companies, and members who are profitable as NFT artists. DAO was the reason why such diverse members gathered together. People from various backgrounds with different borders will make the maximum contribution they can for a certain purpose while working freely. The strong experience of DAO such as Developer DAO and Snapshot gathered members. The Japanese community of Stacks is booming, but we think there is still a shortage of developers. Therefore, we will increase the number of talented Japanese engineers who can experience the Stacks ecosystem, develop Dapps on Stacks, and participate in accelerators. We are confident that this culture of DAO will become the norm as a way of working in the future and we would like to take the world one step further in that direction.

**Comment by louiseivan** [comment]
Translations are usually under Chapters. cc: @D 💎  For grants, we should always think along the lines of managing programs instead of people; if we're focusing on bringing more developers into the ecosystem, what are the programs we can establish locally that can scale and are of high potent, rather than having one-time hackathon with no clear ROIs. How do we make these hackathons sustainable on their own?

We're all for investing in infrastructure such as doc translation, but this needs to be coordinated within the ecosystem, so we don't duplicate effort, sleepi (sleepi#1724) and Jonathan (2n10se#5020) are leading translations; you all should collaborate on it. I can intro if need be then from there we can scope out what's a priority in terms of translation.

**Comment by d-jewel** [comment]
It is rather a partnership to bring in engineers in that community into Stacks and into Stacks Japan Community, then build on Stacks. I believe it's a smarter way rather than finding a new group of engineers from the scratch. I've concluded that this initiative needed an organized approach with steps to follow to lead to fast and successful results hopefully by Q2 this year. 

Projects built by Japanese devs or teams, will certainly attract attention from overall Japanese crypto community and will have a massive network effect going forward. For example, CityCoin project (hopefully TokyoCoin) I'm also working on will also have a similar impact. If successfully launched, we will have strong CityCoin Japan community along with Stacks Japan Chapter, like ALEX Japan, which I'm proud to claim it's a very strong community. 

What we proposed is to build "localized dev infra in Japan". 
Educational contents and sessions focusing on devs require professional touch and that's why I decided to team up and bring in those devs into Stacks. **This is not just a translation but dev contents with extra explanation added by local developers to help with new developers build better understanding**. 
Also, this will be followed by hackathons potentially in collaboration with Stacks Accelerator and other Stacks entities. Winning teams will challenge themselves to apply for Stacks Accelerator programs and some might apply for Stacks Resident program, or even Hiro. Right now there is none. 
**When it comes to introducing something in Japan, localization is the single most important aspect one should consider first, and that's what we are trying to establish this in the first place.**  

We will be organizing a series of events and sessions, to make it sustainable:
- Organize workshops and teach-in sessions in collaboration with devs who are already active in Stacks community
- Continuous exchange of opinion on how to drive going forward with Stacks Foundation, which will be through me 
- Hackathons will run for 1-2 months, relatively longer period, and latter part will be coupled with mentorship by experienced devs on Stacks, which we plan to organize going forward
- Those who win hackathons will be supported to actually establish and deploy on Stacks
- Continuous seminars as well as recorded sessions for late comers will continuously be provided

Also, they had similar experience with other chains like ICP, Cardano, and Astar, supported by each foundation and now they want to establish this for Stacks.

**Comment by will-at-stacks** [comment]
Hi @enmaidao - 

Very sorry for the delay in getting this reviewed.  At this time we are going to reject the grant as we already have some translation efforts underway and a group in Japan that we've been working with on some similar efforts.  However, I would like you and your team to email me at will@stacks.org so I can connect you to those teams and figure out how we can best revise your grant application so that it compliments the work they have planned.  I look forward to speaking with you soon.

Best,
Will

**Comment by neonflux-io** [comment]
Hi @enmaidao, I’m interested in the goal of growing the Stacks developer ecosystem in Japan.

I have experience with Web3, full-stack development, smart contracts, developer tooling, and technical education. I realize this grant was not funded because similar localization efforts were already underway, but if the Japan community is still active, I’d be interested in helping with developer workshops, example dApps, documentation, or hackathon mentorship.

Are there any current initiatives where additional technical contributors are needed?

**Comment by neonflux-io** [comment]
Hi @enmaidao, I’m interested in the goal of growing the Stacks developer ecosystem in Japan.

I have experience with Web3, full-stack development, smart contracts, developer tooling, and technical education. I realize this grant was not funded because similar localization efforts were already underway, but if the Japan community is still active, I’d be interested in helping with developer workshops, example dApps, documentation, or hackathon mentorship.

Are there any current initiatives where additional technical contributors are needed?

**Comment by neonflux-io** [comment]
Hi @enmaidao, I’m interested in the goal of growing the Stacks developer ecosystem in Japan.

I have experience with Web3, full-stack development, smart contracts, developer tooling, and technical education. I realize this grant was not funded because similar localization efforts were already underway, but if the Japan community is still active, I’d be interested in helping with developer workshops, example dApps, documentation, or hackathon mentorship.

Are there any current initiatives where additional technical contributors are needed?

**Comment by neonflux-io** [comment]
Hi @enmaidao, I’m interested in the goal of growing the Stacks developer ecosystem in Japan.

I have experience with Web3, full-stack development, smart contracts, developer tooling, and technical education. I realize this grant was not funded because similar localization efforts were already underway, but if the Japan community is still active, I’d be interested in helping with developer workshops, example dApps, documentation, or hackathon mentorship.

Are there any current initiatives where additional technical contributors are needed?

**Comment by neonflux-io** [comment]
Hi @enmaidao, I’m interested in the goal of growing the Stacks developer ecosystem in Japan.

I have experience with Web3, full-stack development, smart contracts, developer tooling, and technical education. I realize this grant was not funded because similar localization efforts were already underway, but if the Japan community is still active, I’d be interested in helping with developer workshops, example dApps, documentation, or hackathon mentorship.

Are there any current initiatives where additional technical contributors are needed?

**Comment by neonflux-io** [comment]
Hi @enmaidao, I’m interested in the goal of growing the Stacks developer ecosystem in Japan.

I have experience with Web3, full-stack development, smart contracts, developer tooling, and technical education. I realize this grant was not funded because similar localization efforts were already underway, but if the Japan community is still active, I’d be interested in helping with developer workshops, example dApps, documentation, or hackathon mentorship.

Are there any current initiatives where additional technical contributors are needed?
