### ISSUE TITLE
[Wish List] Moodle Authentication Plugin

### ISSUE THREAD

**Issue by friedger** [stacksgov/Stacks-Grants#28]
## Background

Blockstack authentication is mainly used by newly build applications that are not well known. Adding support for Blockstack authentication to a well known application or platform can bring more users to use a "Bring your own ID" account.

Moodle is such a platform that
1. is open source, 
1. allows to add authentication through 
1. is use globally
1. educated students

## Project Overview

The project is about creating an authentication plugin for moodle.org. Serving an moodle instance using the plugin should be done as well.

## Scope

Follow the instruction at 
```
https://docs.moodle.org/dev/Authentication_plugins
```
and build a blockstack auth plugin in PHP.

## Budget and Milestones

??

## Team

??

## Risks

Missing knowledge about moodle in the blockstack community

Moodle uses PHP

## Community and Supporting Materials

None yet.

**Comment by ryanarndtcm** [comment]
Hey Friedger, this is great to see! If you can give an estimate of what you think will be necessary for time/budget and team, that would go a long way to getting next steps toward an approval. Thanks!

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
