### ISSUE TITLE
Stx dev hub similar to aws loft in Princeton 

### ISSUE THREAD

**Issue by doranaj** [stacksgov/Stacks-Grants#281]
**Background**
Actual in person learning and building. Lots of possibilities for growing the space. In person > discord /remote .

Why Princeton:
Our roots (@founder)
Equidistant between two major cities (nyc, Philly)
Talent rich area akin with next gen mindsets.

**Project Overview**
Home/catalyst for next growth phase for stx.

If this is something the team is interested, we can get more granular.

**Comment by will-at-stacks** [comment]
Hi @doranaj Thank you for the proposal.  This is an interesting sounding proposal.  We would certainly consider it if you were to submit a complete application.  Thanks! Will

**Comment by doranaj** [comment]
@will-at-stacks estimates for 2 & 3 yr outlooks - cheer
[proposal_01.2.pdf](https://github.com/stacksgov/Stacks-Grants/files/8050924/proposal_01.2.pdf)

**Comment by will-at-stacks** [comment]
Hi @doranaj -
Thank you for your efforts on this thoughtful proposal.  After discussing this internally, we feel its better to focus event based funding like this in a 'plant many seeds' approach. i.e. Support many small events at many locations around the world - rather than investing so much capital into one location.  However, if you have interest in hosting meet-ups or smaller one-off events in the Princeton area - please let us know.  Thanks, Will
