### ISSUE TITLE
[Wishlist] Catamaranswaps.org UI upgrade

### ISSUE THREAD

**Issue by friedger** [stacksgov/Stacks-Grants#285]
**Background**
catamaranswaps.org is an open source UI for various catamaran and atomic swaps. The UI is not very user-friendly and the experience not user oriented.

**Project Overview**
catamaranswaps is a react app with source code hosted at https://github.com/friedger/stacks-swaps. The contracts' source code is available at https://github.com/friedger/clarity-catamaranswaps
The frontend is using micro-stacks to interact with the stacks blockchain.

The project would simplify the UX and modernize the design

**Scope**
* A modern responsive design
* Frontend implementation of the design
* Create a reusable Swap react component

**Budget and Milestones**
This is a wishlist proposal

**Team**
This is a wishlist proposal

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

The swapping contracts are used daily as can be seen in the explorer.

**Comment by jruffer** [comment]
Our designers would like to take a stab at phase one of this wishlist.  We would like to put together 2 or 3 designs and present them to the community.  In order to do this, we would need some help from users on recording how it is used today and how it should be used if there are issues. 

I would say we would need 40 hours for R&D and then 100 hours for wireframes/hi-def/Figma options from the UI/UX team. 

Phase one would be and ask for $14,000 USD

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
