### ISSUE TITLE
[Wish List] Blockstack Connect Forum Plugin

### ISSUE THREAD

**Issue by ryanarndtcm** [stacksgov/Stacks-Grants#29]
Background: What problems do you aim to solve? How does it serve the mission of a user owned internet?

- Login to the Stacks forum using the new Blockstack Connect login

Project Overview: What solution are you providing? Who will it serve?

- this would serve all folks who previously had logged in to the forum with their Blockstack ID using the old and now unsupported Blockstack Forum plugin

Scope: What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

- The previous version was written in Javascript and Ruby. The final deliverable will allow a test of 10 users from the community who are able to use their Stacks ID to log in to the forum. This will also need to work after Stacks 2.0 launches and beyond.

Budget and Milestones: What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

- 8 hours estimate to get it set up, and then an ongoing community maintenance grant. The maintenance grant would be for an estimated 2 hours a month to test and keep the code up to date.
- budget - $600 to get first 8 hours started. 
- 150/month for maintenance for 6 months as a starting point.

Team needed

- Ruby/Javascript developer
- Community testers

Resources
https://github.com/blockstack/connect

**Comment by friedger** [comment]
More resources related to the previous version: 
* https://larrysalibra.com/adding-blockstack-auth-to-discourse/
* https://github.com/blockstack/omniauth-blockstack

**Comment by wileyj** [comment]
Thanks @friedger ! one more: 
https://github.com/blockstack/discourse-blockstack

This is the plugin that was used previously for discourse

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
