### ISSUE TITLE
Merchant Section: Bitcoin Design Guide

### ISSUE THREAD

**Issue by beanandcheeseburrito** [stacksgov/Stacks-Grants#297]
_Special thanks to Will Corcoran and Brittany Laughlin for their time, consideration, and feedback on this project._

**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

While the Bitcoin Design Guide quickly grows into an incredible resource towards mass adoption it is currently missing a significant section; merchants. Over 12-24 months BTCPay merchant experiences could be documented and iterated upon in order to provide a framework to fill this critical gap in the design guide.

**Project Overview**
What solution are you providing? Who will it serve?

The findings will inform an evolving merchant section in the Bitcoin Design Guide and could focus on accepting bitcoin, understanding the relevance of bitcoin for individuals and businesses, and the basics of lightning. We need to have thoughtful and well tested information freely available that extends beyond payments and aims to provide clarity for merchants sending and receiving funds. The primary use case will be BTCPay as an initial focus and the long term goal would be a generic resource for anyone designing merchant tools.   

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

Improving UX is broad and encompasses a wide scope of skills. Merchants can’t be expected to do it all alone. Implementing a first principles approach will provide measurable pain points and allow open source bitcoin designers and developers to take actionable steps towards smoothing out the merchant experience. A hopeful outcome would be continuing to foster a lasting relationship between the Bitcoin Design Community and BTCPay so that we can provide free and censorship resistant peer to peer transactions to a growing group of global users as adoption increases. A successful merchant section would be defined by distilling information into clear content in the design guide which lowers the barrier to entry that has previously been perceived as too technical, non-supportive, or vague.

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Executing this project well would require full time focus for at least 1 year (ideally 2 years). With a 500k grant a Merchant Section in the Design Guide could accelerate the onboarding of new designers, improve overall adoption of better design processes and significantly grow design & development of applications- immediately.

Total Grant Request: 500k. Given the volatile nature of Bitcoin (which is perfect by design) it is difficult to anticipate how transactions and point of sale will play out. I’d love to set a budget for each milestone but given the nature of the research it makes more sense to have the total amount liquid from the beginning and allocate per milestone as necessary given the tides of market. 

M1. Overview: Learning from the past to inform the future.

M2. Types of Users: Defining merchant personas. 

M3. Barriers to Entry: Identifying perceived pain points.

M4. Getting Started: Resources for accepting bitcoin.

M5. Network Basics: Understanding lightning for merchants.

M6. Why It Matters: Exploring motivations for accepting bitcoin.

M7. Overview: Building for merchants new to lightning.

M8. Communication with Users: Addressing personas and needs.

M9. Supporting New Users: Aiming to work through pain points.

M10. Meeting Basic Needs: Successful ways to accept bitcoin.

M11. Ensuring Competencies: Simplifying lightning for merchants.

M12. Why It Matters: Instilling motivations for accepting bitcoin.

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

I will be building this. My terminal degree is a MPS is Communication Design from Parsons School of Design. I have lead UX strategy for agencies over the years and have about a decade of experience at Stanford University. The past five years have offered me a chance to dive deeper into the open source world and contribute to a number of wonderful Bitcoin projects. My skills are perfect for this project but nothing compares to the amazing feedback the Bitcoin community so generously provides. 

You’ll likely finding me contributing here: https://bitcoin.design/ and https://btcpayserver.org/

This year I’m also a volunteer Design mentor at a fantastic Bitcoin focused initiative: https://www.summerofbitcoin.org/

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

To be honest, there are still many sociopolitical barriers to owning and using bitcoin. While I remain optimistic I must acknowledge that both the asset and the network have legal implications and/or tax penalties that make improving usability extremely difficult. I want to approach this issue with intellectual honesty- I don’t know what the global political spectrum of Bitcoin will be like tomorrow. Still, I remain incredibly optimistic about the future. My biggest contingency plan is just to remain cautious but focused on building out UX resources that Bitcoin so urgently needs to reach the next billion people. 

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

I love contributing to FOSS Bitcoin projects like Bitcoin Design and BTCPay Server. From the beginning I valued community feedback and asked members for their thoughts on the project. Community calls have been amazing ways to have an honest dialogue. All calls are recorded and made public; I am more than happy to share links. Additionally, I have transcribed calls to make conversations visible to all. Through GitHub and Figma, progress can be shared and built on top of. Files are all collaborative and easily editable. I truly want this to be a useful asset to builders and sellers so input from others is incredibly powerful and very much appreciated.

**Comment by will-at-stacks** [comment]
Hi @beanandcheeseburrito -

So glad you submitted.  A couple of items:  Can you please revise this application to reflect the initial scope: $50k for the discussed initial draft of the design guidelines?  Also, can you email me your discord username?  We are moving over to a new grants management dashboard soon and it will use discord for validation.

Also, @blocks8 Brittany has offered to serve as an advisor on your project if that is of interest.  She has lots of experience raising capital and will be able to help you game plan the best way to shape the first $50k grant so that it can be used to raise the full $500k you are seeking.

If you can just comment here after you revise the application, that will help me know to start our review.

Best,
Will

**Comment by beanandcheeseburrito** [comment]
Hi Will,

Item 1. Submission Edit: The budget will be 50K as an initial kick off. These funds will develop a foundation for the project that will provide context for funding the entirety of the research and testing over the next 2 years.

Item 2. I will definitely email you my Discord name for validation.

Thank you @blocks8!

**Comment by beanandcheeseburrito** [comment]
Milestone 1: Overview: 
Learning from the past to inform the future

I plan to deliver the following before the 1st $12,500 payment is released:

1. Understand through conversations with users if their fears come from a lack of design or the technology itself. 

2. Solve issues through the interface and identify other problems we need to tackle to help people feel more comfortable with the technology

3. Research motivations for people accepting bitcoin, what it takes for them to accept bitcoin, how are they first onboarded, and what are their misconceptions. Next, find out how app designers and developers could clarify issues so that a new merchant being onboarded could understand better. Finally, look into how users could better understand the flow. 

Milestone 2: Types of Users: 
Defining merchant personas

I plan to deliver the following before the 2nd $12,500 payment is released:

1. Create user journeys for primary, secondary, and tertiary merchants. 

2. Consider hierarchy for merchants. What kinds of people will be addressed? Shop owners? People sharing something with their own community?

3. By meeting with activists we can learn how to best assist the individual and through working with local businesses in communities currently using the lightning network we can better understand business needs.

Milestone 3: Barriers to Entry Pt. 1:
Addressing perceived pain points

I plan to deliver the following before the 3rd $12,500 payment is released:

1. What does the point of sale terminal look like? What does the back office (from the merchant’s side) of the point of sale look like? 

2. How is UI designed to meet needs? Why did people stop accepting? 


Milestone 4: Barriers to Entry Pt. 2: 
Addressing perceived pain points

I plan to deliver the following before the 4th $12,500 payment is released:

1. Who in the company has controls to the keys?

2. In which languages would the merchant section increase inclusion and make learning more accessible?

3. How can these findings inform an information architecture so that designers may improve the overall business experience with regards to accepting bitcoin?

**Comment by will-at-stacks** [comment]
Hi @beanandcheeseburrito  - 
Thanks very much for the proposal.  We are very excited to support this effort and help you further the advancement of UX/UI design guidelines in the world of digital payments, specifically Bitcoin and Lightning wallets.  We are also excited to work with you at the conclusion of this grant in additional fundraising efforts to support the full project and maximize the impact of your work.  

In addition to the milestones laid out above I just want to note that the grant will yield an outline presentation booklet and/or presentation of some sort to assist with your fundraising efforts.  Lastly, per our earlier conversations we will ask that you present your work to the Stacks (and hopefully broader Bitcoin) community so that you can share your methodologies and findings with other designers and technologists.

Provided this is all acceptable to you, we are thrilled to approve this grant!

Please let us know when you are ready for your milestone 1 review.

Best,
Will

**Comment by beanandcheeseburrito** [comment]
Thank you so much, Will! Milestone 1 will tentatively be completed by 3/18. I will keep you updated on progress.

**Comment by beanandcheeseburrito** [comment]
Took the past month to focus on milestones 1-3. User research from 62 individuals and businesses informed findings. Posted moments ago to the Bitcoin Design Community: https://github.com/BitcoinDesign/Guide/pull/741

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will

**Comment by beanandcheeseburrito** [comment]
Thanks Will. Looking forward to checking out the new Grants Dashboard. Congratulations on the launch!
