### ISSUE TITLE
Songs To Radio (Extension from first Application) #252

### ISSUE THREAD

**Issue by JacobRyan258** [stacksgov/Stacks-Grants#307]
Background
What problems do you aim to solve? How does it serve the mission of a user owned internet?
This application is a continuation of our first grant application #252 – please refer to this grant application for more background information. 
The problem Songs To Radio Protocol aims to solve is decentralizing the music industry and creating user owned royalties secured by Bitcoin via the Stacks blockchain. Since we began design of UX/UI – and development of design, we are very close to having M1 completed. That said we thought it would be great timing to show a few videos with the community of the design, any comments are welcome for feature adds, feedback, or questions. These are loom videos that show the design, and development is currently very close to matching design and has been shown to Stacks Foundation team members. Video 2 is an extension of #1, so please watch in order.
1.	https://www.loom.com/share/a344f9cb070e44a8b90587c83b6c2606
2.	https://www.loom.com/share/f613039559aa4a239cef238c5db80847
The design was professionally done by @AJ_Ayanbisi on Twitter, I would highly recommend his services for anyone building applications who may need professional design for UX/UI.
The protocol will allow for STR (Songs To Radio - STR for short) tokens to be used in several different ways. The PoX consensus will allow for the token to be stacked to earn STX rewards, and this will also allow for DeFi of music ownership to come to fruition for the first time.
With the Proof of Concept and MVP frontend build very close to complete, it is time to focus more heavily on next steps! 

Project Overview
What solution are you providing? Who will it serve? 

This is providing a solution to the music creation, ownership, and distribution from the ancient ways of the past/present to a more decentralized, permission less, and innovative environment. The protocol aims to benefit token stackers and NFT owners from the PoX built in functionality that The Stacks Blockchain provides and with the security of The Bitcoin Network. The protocol will serve individuals who want to own a passive form of income like music royalties from successful artists of the protocol. This will also benefit hundreds and thousands of musical artists, managers, and agents who are being blocked by centralized members of the established music industry. Large corporations and insurance companies invest into music royalties, so why not allow the same for the direct fans of their favorite artists and allow for a DeFi protocol to be built around that?

Scope 
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success? 

This is a continuation from Stacks Grant #252 so success will look like what is defined there. We are currently shifting focus toward backend, smart contract, and API development from initial design and front-end development of said design. Success of this grant will be the live application with deployed smart contracts to test net that displays this protocol. After a bug bounty, we will hold a mainnet launch upon corrections of any and all bugs found. The success measurements will remain similar to what was mentioned there. 

Budget and Milestones 
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone. 
Total budget $35,000 over the course of 2-3 months. When we say months, we refer to full-time hours being put in so 30-40 hours per week for 4 team members.

M2: Complete MVP – 
Scope: During this phase of development, we will be focused on launching to testnet our smart contracts that deal with the open marketplace and NFT sales/royalty distributions. Artists will be able to mint a song for a single user to own/collect, or upload a collection of cover art to represent royalty ownership based on artist royalty distribution preference. 
Deliverables: 
1.	Users will be able to create an account with STR
2. mvp will include user login flow, user dashboard displaying owned NFTs, and marketplace of music/song NFTs available on the STR marketplace. 
3.	Testing of all of the initial application smart contracts on testnet from Stacks Foundation/Any other community members who wish to provide feedback
Estimated time: 2 months and portion of the Grant budget: $35,000.00

Total Budget - $35,000

Team
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share previous work.
The team has been expanded, it is led by myself (Jacob Ryan) @JacobRyanMedia on twitter and  https://github.com/JacobRyan258 on github. I just finished Clarity universe the 2nd cohort. The team has 3 full-stack developers currently working on the project, a lead designer @AJ_Ayanbisi on Twitter. We will expand on team growth with this grant to onboard to the team an additional smart contract developer by M2. Please see #252 for any additional information.

Risks
What dependencies or obstacles do you anticipate? What contingency plans do you have in place? 
The risks remain the same for #252 which are that users may not fully understand the value the protocol will bring initially. We will have full documentation, educational pieces put together (outside of the grant), and other content (outside of the grant) for users to understand better PoX, Stacks Blockchain, and many other topics that currently have a lot of questions around them for new users. Our goal is to educate and show the value that the Stacks blockchain and PoX consensus brings to crypto. 

Community and Supporting Materials 
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?
I have asked a handful of community members to look at the initial design and where we are in development for feedback. Every member that has had a chance to review, has provided positive feedback and can’t wait to see further development. We are planning to launch very soon, a hosted website informing users of the application, and a way to provide an email address to stay informed which will allow for us to create a testing group of sorts once we are ready to put out the application to testnet for the bug bounty. 

We are very open to community feedback, you can email me at [jacobryan258@gmail.com](mailto:jacobryan258@gmail.com) or dm me on twitter @jacobryanmedia for a demo of where we are at in development at any time.
Thank you,
Jacob and the STR team 😊

**Comment by will-at-stacks** [comment]
Hi @JacobRyan258 : 

Thanks very much for this application.  We are big fans of this project and think its a great use case to demonstrate the value of Stacks to new users.  However, we feel the current application needs to be broken up into two grants.  We would like your next grant to be budgeted so that you can successfully complete the MVP.  While we don't have the insights into the project that you do, our recommendation would be to defer the following scope items to a later date so you can successfully complete the MVP:

**- From M2:**
- Users will be able to customize their profile
- Users will have a learn more page guiding them on how to and why they should download the Hiro wallet.
- Once they link their Hiro wallet to their web 2 like account, they will have the option to keep their web 2 data in the application database, or delete it from the Database.

**- From M3:**
- Bug bounty

**- From M4:**
- All items

We very much want this project to be successful, so please budget for your team to build the Minimal Viable Product (only the critical user flows) and have that MVP tested by a sizable group of users including someone from the Accelerator and other product experts in the Stacks ecosystem (we can assist in setting this up if need be).  Once that is completed and you synthesize the feedback + proposed next steps, we feel that will make the scope of any required third grant apparent. 

Best,
Will

**Comment by JacobRyan258** [comment]
Hi @will-at-stacks - thank you for the feedback - we are agreeable to all feedback! I have updated the grant proposal to reflect suggestions made. We will be able to provide the MVP with the new structure. 

I will reach out as soon as we are ready to provide testing of the MVP by the sizable group of users mentioned and the Stacks Accelerator!  

Thank you,
Jacob

**Comment by JacobRyan258** [comment]
Hi @will-at-stacks, just wanted to follow up to see if there is anything additional I need to do on my end to move forward? 

All the very best,
Jacob

**Comment by will-at-stacks** [comment]
@JacobRyan258 thanks for making the requested revisions. Sorry for the hold up.  We are v.busy these days ;). Which is a good thing!  This is approved.  Onward!

**Comment by JacobRyan258** [comment]
Yes indeed it is a great thing that things are busy, means excellent growth and exciting things happening within the community :)! 

Just for clarity on the two payments - what is to be delivered in order for the second payment to be disbursed? Just would like to have an understanding - I am agreeable of course, again just wanting to know!

Thank you and all the very best,
Jacob

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
