### ISSUE TITLE
Miner Price Prediction Game and Marketing Campaign

### ISSUE THREAD

**Issue by friedger** [stacksgov/Stacks-Grants#37]
## Background

> What problems do you aim to solve? How does it serve the mission of a user owned internet?

One part of Stacks miners' activity is to predict the price of STX/BTC. Users and miners should be made aware of it. 

## Project Overview

> What solution are you providing? Who will it serve?

This proposal is about adding STX price prediction game to the existing price prediction site cryptopick.net The site provides different games about price development within an hour, a day or week. It also provides tournaments for a sequence of these games. The site has already integrated STX token as part of the top 200 tokens game. 

## Scope

> What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

**Specs**
1) The site will add a game to predict whether the price of STX/USD (or STX/BTC) will go up or down within a day. 

2) The site will add 5 tournaments for the daily price prediction over the period of one month. Each tournament has a prize pool of 200$ (or the equivalent in BTC or STX) 

3) The site will provide a short description of Stacks and where to find more information about mining and stacking 

4) The team will inform their user base of ~ 15k users about the tournaments. 

**METRICS**
* Number of users of the daily game
*  Feedback from miners about the usefulness of crowd knowledge. 

## Budget and Milestones

> What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Amount: 1250$

The project has only the scoped activities to be setup once. 

Weekly payout of tournament prize. 

## Team

> Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community?

The cryptopick.net team [@CryptoPickHQ (twitter)](https://twitter.com/CryptoPickHQ)

This project will be lead by @mrcryptorisin (telegram). 

Friedger Müffke will provide relevant information to the team. 

## Risks

> What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

The site currently provides only price pair information in USD. The team might not be able to add the price pair STX/BTC. In that case the daily game would be about STX/USD

The site currently pays out prizes in ETH. The team might not be able to add prize pool values in BTC or STX. In that case the price would be paid in USD and distributed through the site in ETH. 

## Community and Supporting Materials

> Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

Cryptopick.net was discussed as a fun game on telegram. 

Cryptopick.net users have already bet on STX in the top200 game.

**Comment by RaffiSapire** [comment]
Hi there, Questions for the team, who we'd like to join this thread and respond. How will you measure success?
Can we communicate directly with the team implementing this? Would like to see them sharing updates?

**Comment by friedger** [comment]
I am sure @GeeVeldek is happy to response here and clarify the details with you. I just wanted to pave the way for the team and the foundation and see how this can work out. Happy if @RaffiSapire takes it from here.

For measuring success, I added two metrics. What would be reasonable values?

**Comment by RaffiSapire** [comment]
Thank you! Hi @Geeveldek please do chime in and thank you for your interest in contributing.

**Comment by GeeVeldek** [comment]
> Hi there, Questions for the team, who we'd like to join this thread and respond. How will you measure success?
> Can we communicate directly with the team implementing this? Would like to see them sharing updates?

Hi there @RaffiSapire, my apologies for the late reply but the past days have been crazy busy.
A quick introduction on my end, I am co-founder and CEO of CryptoPick.

Measuring this campaign's success is key for you guys but also for us because it is new for CryptoPick. We have received many requests for sponsorship/publicity on CryptoPick in the past. Still, as we were building and validating our game, we felt like there were not enough players participating. This has clearly changed over the past months. We went from 500 registered players back in May to 15k+ right now with over 1000 active players and an average of 300 participants in each Tournament (this may vary from 200 to 600 depending on the tournament type). 

So how do we measure success?
1) Track the number of players who click on the Blockstack link to know more about Blockstack.
- We will add this link on top of a short description of what Blockstack is inside the sponsored tournaments.
- We will also announce these special sponsored tournaments on our Social Media, including the link.
- We will also send out an email to all our users (15k+) to announce these sponsored tournaments, including the link.

2) Track the number of players who make predictions on STX/BTC going up or down in price.
On top of sponsored tournaments, we will also add STX to the UP/DOWN game, which means many people who play UP/DOWN but don't necessarily participate in tournaments will also see STX and potentially discover what it is. Seeing all of a sudden, the CryptoPick players will be confronted with STX in several places. The number of people who predict the price could also grow, but only the future will tell.

3) Track the accuracy of the predictions.
This one is a bit tricky as this is pure wisdom of crowd data, and we are not giving access to a crystal ball that will predict the future. Nevertheless, it will be exciting to see how these predictions evolve.

There might be some other options. I would love to hear your ideas, as well.

It could be interesting to jump into a call to discuss this further.

Happy New year!

**Comment by RaffiSapire** [comment]
Hi there, unfortunately, we're going to pass here. It's out of scope of the grant program which is funding community resources (e.g. education), infra development, dapps, and developer tooling. However, Freehold is a community that is token-oriented, and we think it would be best for you to reach out or freehold. Reach out to Louis on discord to share more with him. Louise Ӿ#3903  on discord!
