### ISSUE TITLE
[Wishlist] Fungible token standard (ie ERC20)

### ISSUE THREAD

**Issue by jeffdomke** [stacksgov/Stacks-Grants#44]
**Background**

This is a simple, but critical, piece of our shared economic infrastructure. Token innovation on Ethereum exploded after a similar standard was established. The real power of such a standard is interoperability across Stacks products and services. Therefore the real work here is building alignment with the Stacks community, documentation, and education.

For reference please see the original [ERC20 specification for Ethereum](https://eips.ethereum.org/EIPS/eip-20). Also see a proposed [SRC20 Clarity trait](https://github.com/psq/flexr#the-src20-token-trait) created Pascal during our Clarity hackathons.

**Project Overview**

**Phase 1: Propose standard**

In the propose phase, teams will specify the contract specifics and present plans to the Stacks community on adoption of this standard: 

- Minting contract example.
- Clarity trait definition and explanation of design choices.
- An example to serve to justify the design choices.
- A Stacks Governance SIP proposal.
- Feedback from developer community.
- Detailed explanation for how wallets and apps would make use of this standard.
- Detailed plan for how you plan to document and help the community coalesce around your token standard: Website, documentation, example code, videos, office hours, etc.

**Phase 2: Roll out standard**

In the rollout phase, the team will finalize feedback gathering from community, document final decisions and produce materials intended to help the Stacks community adopt the standard. 

- Complete activities described in propose phase such as documentation. 
- Help new developers or integrators adopt your standard, serving as a “point-person” for help, questions, or evolving the standard as needed.
- Share a completion report with the Stacks community summarizing the project and what future efforts, if any, might look like.

**Recommended team**
This project will require expertise with smart contracts, Clarity, and the Stacks community. 

**Recommended grant**
$3,000 USD

**Comment by hstove** [comment]
I've taken my approach at starting the work to define this standard in https://github.com/stacksgov/sips/pull/5. I am not interested in pursuing the financial reward for this grant. In fact, @jeffdomke has proposed many additional requirements in this grant. I would be more than happy for others to build off of my proposal, and then build out the examples, marketing materials, test cases, docs, etc, that Jeff has outlined here. If someone was to do that work, they should get this grant, regardless of if it uses my proposal or not.

**Comment by jeffdomke** [comment]
Awesome thanks @hstove

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
