### ISSUE TITLE
[Wishlist] Collateralized Bitcoin asset on Stacks (ie RenBTC or tBTC)

### ISSUE THREAD

**Issue by jeffdomke** [stacksgov/Stacks-Grants#46]
**Background**

Bitcoin is exceptionally valuable, but also exceptionally limited by design. To realize the full potential of innovation on Bitcoin, we need a reliable and safe way to move Bitcoin onto Stacks and vice versa: We call this asset xBTC. Once we can mint xBTC on Stacks, Bitcoin innovators will have a wide-open design space for new products and access to an untapped market of Bitcoin capital. 

More liquidity lowers the barrier to adoption. We’ve seen similar bridges exist between Bitcoin and Ethereum such as [tBTC](https://tbtc.network/) and [RenBTC](https://renproject.io/).  But out of all blockchains, Stacks is uniquely positioned to implement a bridge between BTC and xBTC because access to Bitcoin block metadata is built-in to the Clarity smart contract runtime.

**Project Overview and Milestones**

**Phase 1: Design**

In the design phase, teams will share their protocol and economic design with the Stacks community:

- Detailed paper rigorously describing the protocol design and system properties, and a detailed description of the token economics. Token economics must account for economic risks and incentivize long term network participation. 
- Public announcement of project.
- The protocol must be resilient, distributed, and tolerant of a wide variety of nodes and node failure modes (within reason).
- Bitcoin and Stacks community evangelism is encouraged. 

**Phase 2: Build**

In the build phase, the winning team technically implement their solution

- Smart contracts published on testnet.  
- Node software complete and on github. 
- Security audits performed. 
- Entire protocol is functional and can be tested. 

**Phase 3: Launch**

In the launch phase, teams launch a complete xBTC product that can mint and release Bitcoin. The approach must incentivize a wide variety of operators to join and sustainably support the protocol:  

- Smart contracts and node software in production. 
- High quality web client must be able to interface with existing Stacks wallet(s). 
- Stacks based asset(s) on mainnet. 
- Protocol must be resilient to plausible failure modes
- Ability to safely port 1 BTC to a Stacks based asset and then release that asset for 1 BTC on Bitcoin. 
- Public launch. 

**Recommended team**

This project will require expertise in Bitcoin, Stacks, token economics, smart contracts, user experience, and marketing. Launching and growing the solution will take many months. An experienced team with a diverse skill set and a long term mentality is encouraged. 

**Recommended grant** 

- I suggest breaking down the project into milestones with evaluation criteria and specific grant awards for various phases such as design, successful launch, etc. 
- $50,000 USD + security audit costs

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
